# Generated by Django 3.2.8 on 2021-10-11 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotels',
            name='division',
        ),
    ]
