# Generated by Django 3.2.8 on 2021-10-13 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_remove_hotels_division'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotels',
            name='division',
            field=models.CharField(default=None, max_length=40, null=True),
        ),
    ]
