# Generated by Django 3.2.8 on 2021-10-13 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_hotels_division'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtypes',
            name='rent',
            field=models.PositiveIntegerField(default=1, null=True),
        ),
    ]
